server {
    listen 80;

    # Servir le dashboard React
    location / {
        proxy_pass http://dashboard:3000;
        proxy_set_header Host $host;
#        proxy_set_header X-Real-IP $remote_addr;
    }

    # Rediriger les requêtes MCP vers le serveur FastMCP
#    location /mcp {
#        proxy_pass http://mcp:8000;
#        proxy_set_header Host $host;
#        proxy_set_header X-Real-IP $remote_addr;
#    }

    location /api/ {
        proxy_pass http://mcp:8000/api/;
        proxy_set_header Host $host;
    }

}
